server:
  port: 9812

spring:
  application:
    name: SECOND-SERVICE
  config:
    import: optional:configserver:http://localhost:8001

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"